server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev
    username: mohirdev
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
upload:
  server:
    folder: /Users/DXM-HP/Documents/upload/
